unidades = [
    "E.M. Almerinda da Rocha Magalhães",
    "E.M. Alzira de Moraes de Matos",
    "E.M. Anízia Rosa de Oliveira Coutinho",
    "E.M. Beatriz Amaral",
    "E.M. Belino Catharino de Souza",
    "E.M. Carlos Vanderson Gonçalves Pereira",
    "E.M. Carmem Regina Ferreira Oliveira",
    "E.M. Edilênio Silva de Souza",
    "E.M. Edilson Vignoli Marins",
    "E.M. Elcira de Oliveira Coutinho",
    "E.M. Ione Pereira Roiz",
    "E.M. Ismênia de Barros Barroso",
    "E.M. Jardim Ipitangas",
    "E.M. João Laureano da Silva",
    "E.M. João Machado da Cunha",
    "E.M. José Bandeira",
    "E.M. Luciana Santana Coutinho",
    "E.M. Lúcio Nunes",
    "E.M. Mª Luiza de Amorim Mendonça",
    "E.M. Manoel Muniz da Silva",
    "E.M. Margarida Rosa de Amorim",
    "E.M. Orgé Ferreira dos Santos",
    "E.M. Paulo Luiz Barroso Oliveira",
    "E.M. Prefº Walquides de Souza Lima",
    "E.M. Prof. Francisco Vignoli",
    "E.M. Profª Maria de Lourdes Melo Paes Barreto",
    "E.M. Profª Osíris Palmier da Veiga",
    "E.M. Rubens de Lima Campos",
    "E.M. Sebastião Manoel dos Reis",
    "E.M. Theófilo D'ávila",
    "E.M. Valtemir José da Costa",
    "E.M. Ver. Ivan da Silva Melo",
    "E.M. Vilatur",
    "C.M Gustavo Campos da Silveira",
    "C.M.E. Jurandir da Silva Melo",
    "C.M.E. Menaldo Carlos de Magalhães",
    "C.M.E. Padre Manuel",
    "Casa Creche Benta de Souza Quintes",
    "Casa Creche Carmo Gonçalves",
    "Casa Creche Daliataria Gomes dos Reis Nascimento",
    "Casa Creche Elda Amorim da Silva",
    "Casa Creche Elizabete Alves da Silva",
    "Casa Creche Elizabete Siqueira Cadena da Silva",
    "Casa Creche Enedina Campos Macedo",
    "Casa Creche Ercy Gomes de Oliveira",
    "Casa Creche Erotides de Abreu Souza",
    "Casa Creche Luciana Madureira",
    "Casa Creche Nazareth Rodrigues Moreira",
    "Casa Creche Nilton Souza dos Santos",
    "Casa Creche Norma Remigio Marinho",
    "Casa Creche Odete Guimarães Santana",
    "Casa Creche Profª. Regina Lucia Coelho Sá",
    "Casa Creche Sebastiana de Oliveira Bravo",
    "Casa Creche Sônia Mendonça de Oliveira",
    "Casa Creche Valdemira Macedo",
    "Casa Creche Ygor Ferreira de Oliveira",
    "Casa Creche Zilda Baptista Correa",
    "Creche M. Amarilis Menezes Vignoli",
    "Creche M. Bicuíba",
    "Creche M. Clementina Melo",
    "Creche M. Domiciana Monteiro dos Santos",
    "Creche M. Edilena Nunes da Costa",
    "Creche M. Maria Eduarda",
    "Creche M. Maria Catharino Gonzaga",
    "Creche M. Melchiades Carlos do Nascimento",
    "Creche M. Nair Aguiar da Silva",
    "Creche M. Osvaldo",
    "Creche M. Padre Rodrigo Marques",
    "Creche M. Profª. Maria Regina Martins Santos",
    "Creche M. Tia Juracy de Freitas Alves",
    "Creche M. Tia Merice Ribeiro de Oliveira",
    "Creche M. Victória Azeredo da Silva"
]

bairros = [
    "Água Branca",
    "Alvorada",
    "Área Rural de Bacaxá",
    "Área Rural de Sampaio Correia",
    "Área Rural de Saquarema",
    "Areal",
    "Asfalto Velho",
    "Aterrado",
    "Bacaxá",
    "Barra Nova",
    "Barreira",
    "Basiléa",
    "Bicuíba",
    "Bonsucesso",
    "Boqueirão",
    "Caixa D'água",
    "Centro",
    "Comum",
    "Condado de Bacaxá",
    "Coqueiral",
    "Engenho Grande",
    "Fátima",
    "Gravatá",
    "Guarani",
    "Ipitangas",
    "Itaúna",
    "Jaconé",
    "Jardim",
    "Leigos",
    "Madressilva",
    "Mombaça",
    "Morro dos Pregos",
    "Parque Marina",
    "Porto da Roça I",
    "Porto da Roça II",
    "Porto Novo",
    "Raia",
    "Retiro",
    "Rio da Areia",
    "Rio Seco",
    "Sampaio Correia",
    "São Geraldo",
    "Serra de Mato Grosso",
    "Tinguí",
    "Verde Vale",
    "Vilatur",
]

distritos = [
    "1º / Saquarema (Centro)",
    "2º / Bacaxá",
    "3º / Sampaio Corrêa"
]
